# Generated by Django 5.0.3 on 2024-03-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compliments', '0002_alter_compliment_compliment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliment',
            name='compliment',
            field=models.CharField(default='Python', max_length=255),
            preserve_default=False,
        ),
    ]
