# Generated by Django 5.0.3 on 2024-03-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compliments', '0003_alter_compliment_compliment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliment',
            name='compliment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
