# Generated by Django 5.0.3 on 2024-03-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compliments', '0004_alter_compliment_compliment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliment',
            name='compliment',
            field=models.CharField(max_length=255),
        ),
    ]
