# Generated by Django 5.0.3 on 2024-03-21 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('academic', 'Academic Program Enhancements'), ('infrastructure', 'Campus Facilities and Infrastructure'), ('outreach', 'Community Engagement and Outreach'), ('technology', 'Technology and Digital Resources')], max_length=50)),
                ('description', models.TextField()),
                ('solution', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicSuggestions',
            fields=[
                ('suggestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Suggestions.suggestion')),
            ],
            options={
                'verbose_name': 'Academic Program Enhancement',
                'verbose_name_plural': 'Academic Program Enhancements',
            },
            bases=('Suggestions.suggestion',),
        ),
        migrations.CreateModel(
            name='InfrastructureSuggestion',
            fields=[
                ('suggestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Suggestions.suggestion')),
            ],
            options={
                'verbose_name': 'Cammpus Facilities and Infrustructure',
                'verbose_name_plural': 'Cammpus Facilities and Infrustructure',
            },
            bases=('Suggestions.suggestion',),
        ),
        migrations.CreateModel(
            name='OutreachSuggetion',
            fields=[
                ('suggestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Suggestions.suggestion')),
            ],
            options={
                'verbose_name': 'Community Engagement and Outreach',
                'verbose_name_plural': 'Community Engagement and Outreach',
            },
            bases=('Suggestions.suggestion',),
        ),
        migrations.CreateModel(
            name='TechnologySuggestion',
            fields=[
                ('suggestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Suggestions.suggestion')),
            ],
            options={
                'verbose_name': 'Technology and Digital Resources',
                'verbose_name_plural': 'Technology and Digital Resources',
            },
            bases=('Suggestions.suggestion',),
        ),
    ]
