# Generated by Django 5.0.3 on 2024-03-21 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suggestions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherSuggetions',
            fields=[
                ('suggestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Suggestions.suggestion')),
            ],
            options={
                'verbose_name': 'Other Suggetion',
                'verbose_name_plural': 'Other Suggetions',
            },
            bases=('Suggestions.suggestion',),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic Program Enhancements'), ('infrastructure', 'Campus Facilities and Infrastructure'), ('outreach', 'Community Engagement and Outreach'), ('technology', 'Technology and Digital Resources'), ('others', 'Others')], max_length=50),
        ),
    ]
