# Generated by Django 5.0.3 on 2024-03-13 12:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rape', 'Rape Complaint'), ('sexual_misconduct', 'Sexual Misconduct Complaint'), ('bullying', 'Bullying Complaint'), ('harassment', 'Harassment Complaint')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('evidence', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='BullyingComplaint',
            fields=[
                ('complaint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentFeedback.complaint')),
            ],
            options={
                'verbose_name': 'Bullying Complaint',
                'verbose_name_plural': 'Bullying Complaints',
            },
            bases=('StudentFeedback.complaint',),
        ),
        migrations.CreateModel(
            name='HarassmentComplaint',
            fields=[
                ('complaint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentFeedback.complaint')),
            ],
            options={
                'verbose_name': 'Harassment Complaint',
                'verbose_name_plural': 'Harassment Complaints',
            },
            bases=('StudentFeedback.complaint',),
        ),
        migrations.CreateModel(
            name='RapeComplaint',
            fields=[
                ('complaint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentFeedback.complaint')),
            ],
            options={
                'verbose_name': 'Rape Complaint',
                'verbose_name_plural': 'Rape Complaints',
            },
            bases=('StudentFeedback.complaint',),
        ),
        migrations.CreateModel(
            name='SexualMisconductComplaint',
            fields=[
                ('complaint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentFeedback.complaint')),
            ],
            options={
                'verbose_name': 'Sexual Misconduct Complaint',
                'verbose_name_plural': 'Sexual Misconduct Complaints',
            },
            bases=('StudentFeedback.complaint',),
        ),
    ]
