# Generated by Django 5.0.3 on 2024-03-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentFeedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rape', 'Rape Complaint'), ('sexual_misconduct', 'Sexual Misconduct Complaint'), ('other', 'Other Complaint'), ('harassment', 'Harassment Complaint')], max_length=20)),
                ('date', models.DateField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('evidence', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BullyingComplaint',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('rape', 'Rape Complaint'), ('sexual_misconduct', 'Sexual Misconduct Complaint'), ('other', 'Other Complaint'), ('harassment', 'Harassment Complaint')], max_length=20),
        ),
        migrations.AlterField(
            model_name='harassmentcomplaint',
            name='category',
            field=models.CharField(choices=[('rape', 'Rape Complaint'), ('sexual_misconduct', 'Sexual Misconduct Complaint'), ('other', 'Other Complaint'), ('harassment', 'Harassment Complaint')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rapecomplaint',
            name='category',
            field=models.CharField(choices=[('rape', 'Rape Complaint'), ('sexual_misconduct', 'Sexual Misconduct Complaint'), ('other', 'Other Complaint'), ('harassment', 'Harassment Complaint')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sexualmisconductcomplaint',
            name='category',
            field=models.CharField(choices=[('rape', 'Rape Complaint'), ('sexual_misconduct', 'Sexual Misconduct Complaint'), ('other', 'Other Complaint'), ('harassment', 'Harassment Complaint')], max_length=20),
        ),
    ]
