# Generated by Django 5.0.3 on 2024-03-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentFeedback', '0002_alter_complaint_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
