# Generated by Django 5.0.3 on 2024-03-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentFeedback', '0002_other_delete_bullyingcomplaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='email',
            field=models.EmailField(default='tnambande@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='harassmentcomplaint',
            name='email',
            field=models.EmailField(default='Python', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='other',
            name='email',
            field=models.EmailField(default='Python', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rapecomplaint',
            name='email',
            field=models.EmailField(default='Python', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sexualmisconductcomplaint',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
