# Generated by Django 5.0.3 on 2024-03-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentFeedback', '0003_alter_complaint_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
