# Generated by Django 5.0.3 on 2024-03-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentFeedback', '0005_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='student',
            name='password2',
            field=models.CharField(default='Python', max_length=255),
            preserve_default=False,
        ),
    ]
